### ISSUE TITLE
locationRules

### ISSUE THREAD

**Issue by faust64** [LemonLDAPNG/node-lemonldap-ng-handler#1]
Hi,

I've managed to get delegate authentication from some piece of nodejs code, to LemonLDAP-NG, using your module. Although I had to patch it:
https://github.com/faust64/node-lemonldap-ng-handler/compare/master...faust64:experimenting

I'm not yet convinced this patch is needed.
Node-lemonldap-ng-handler readme states:

> Rules and headers must be written in Javascript, not in Perl [...]

For the record, the locationRule defined for my app looks like:

`locationRule: {"myapp.exampole.com":{"default":"accept"}}`

Which sounds like a valid javascript, yet doesn't look like the sample given in your readme.
Having tried to edit that rule such as:

`locationRule: {"myapp.exampole.com":{"^/public":"skip","default":"accept"}}`

I'm still prompted for authentication loading files fro my `/public` folder. So I'ld guess my location rules are not even processed.

Any idea what could I be doing wrong?

Thanks

**Comment by guimard** [comment]
Hello,
`skip ` management fixed in e2d0413 (bad value). I don't agree with your patch but I've done some optimization in previous commit (c33055e).
Thanks four your report !

**Comment by guimard** [comment]
Stay this opened until  @faust64 test it

**Comment by faust64** [comment]
Checking out today, I confirm my patch's no longer needed for my users to authenticate.

On the other hand, I still haven't figured out how to define my locationRules to skip authentication on some path served by express.
Having tested both your commits, setting my locationRule to skip on `"^/public/.*"` or `^/public"` same behavior : getting `/public/somescript.js`, I'm redirected to LLNG authentication page

I might troubleshoot further later. Considering I don't intend to serve static assets using nodejs/express, it's not a big deal right now.
Thanks!

**Comment by guimard** [comment]
Fixed in 0.3.0

**Comment by faust64** [comment]
works perfectly, thanks again!
